### ISSUE TITLE
Use as a CLI builder

### ISSUE THREAD

**Issue by juanibiapina** [cv/sd#5]
My use case is to have `sd` as a entry point called from a bash script, in order to provide a good nested command CLI. The user should not know this is used under the hood.

For that I need at least two things I can think of now:
- Not include the "~/.sd" folder and potentially not even `SD_PATH`
- Communicate to the subscripts what the root path of the cli is

Do you think these things make sense or should I look for a different tool?

**Comment by cv** [comment]
After a bit of user testing here, I got the same requirement, too: people love sd, but hate having to refer to it as a separate entity in the system.

There are a few possible avenues:

- Turn off `~/.sd` and `SD_PATH` lookups entirely, and rely on a shell alias to make the path to the scripts dir explicit (something like `alias foo="sd --path ~/src/script --alias foo"`, which would still require fiddling with `.bashrc` and the like, but be the simplest implementation)

- Use something like [go-bindata](https://github.com/jteeuwen/go-bindata) or [go-basher](https://github.com/progrium/go-basher) to turn `sd` into a part of a build system of sorts. You'd point at the scripts dir during compilation and it would spit out a self-contained binary, which you could then ship. This would probably require reengineering sd into a build tool, but allow for zero-config installs (at the cost to the scripts developer, who'd have to do some build engineering too).

Thoughts, @juanibiapina and @divoxx?

**Comment by divoxx** [comment]
Another option is to turn `sd` into a development dependency instead of a runtime dependency.

The dev working on a CLI would invoke `sd generate` or something, and it would generate all the necessary bash scripts, such as the entrypoint/executable, libexecs and the bash/zsh completion.

For example, let's say you run `sd generate`, it would output the following files within the project folder:

* bin/mytool
* libexec/mytool/subcommand.sh
* libexec/mytool/subcommand2.sh
* share/bash-completion/completions/mytool

After that point, the devs can just distribute them however they seem fit and since its compatible with POSIX, the generated files can be easily be packaged to simply be extracted on a prefix such as `/usr` or `~/.local`, etc.

It also allows for it to simply be standalone scripts within a repository if the tool is simply used in the context of a repo. 

For reference, that's what git does for example. `git diff` is really executing `/usr/libexec/git-core/git-diff`, etc.

**Comment by juanibiapina** [comment]
I like your first option because there's so little extra coding involved. As a CLI developer I would instead of doing an alias, provide an entry point "my-cli" which would itself invoke sd with the correct option and set other configuration variables my CLI needs. So still a runtime dependency, but no need for the user to know how it is used.

**Comment by juanibiapina** [comment]
As it turns out, after a bit of testing on my side as well, many users want to to have extra commands that they are not ready to share yet, so it seems like having the home dir path is a good idea.

**Comment by cv** [comment]
@juanibiapina if I move the logic that parses the `SD_PATH` env var to the `--path` argument, would that fit your use? You could still load scripts from `~/.sd` by doing something like `sd --path "/usr/local/whatever/scripts:~/.sd" …`.

**Comment by cv** [comment]
@divoxx that's a cool idea, but it'd require rewriting large chunks of sd so it works in a more static fashion. Need to think it through. Maybe for 2.0 ;)

**Comment by divoxx** [comment]
@cv makes sense.

I might be missing something but what exactly does passing `--path` instead of setting `SD_PATH` bring to the table? 

If the idea is to call sd from within your CLI script entrypoint, the same can be done right now just by setting `SD_PATH` prior to calling sd, which can be vendored inside the project folders, no? Something like:

```bash
base_path="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
export SD_PATH="${base_path}/scripts"
eval "${base_path}/sd" "${@}"
```

**Comment by cv** [comment]
@divoxx good question, and I wondered that, too (and you don't even need an entry-point script, or to export `SD_PATH`. Nothing wrong with `SD_PATH=… sd "${@}"` as the command in an alias, unless you don't know where your `scripts/` dir lives, which might be the case.)

**Comment by divoxx** [comment]
@cv the alias would require the user to have to configure it and add to their bashrc, what I meant is having an entrypoint inside your project that wraps the whole thing and sets SD. That way sd is a project dependency but invisible to the user.

**Comment by juanibiapina** [comment]
I wanted to *remove* the option to add extra paths in the beginning. But it turns out people like it better this way.

**Comment by juanibiapina** [comment]
Closing old issue.
